server:
  port: 8080

spring.h2:
  console:
    enabled: true

spring.datasource:
#  driver-class-name: org.mariadb.jdbc.Driver
#  url: jdbc:mariadb://127.0.0.1:3306/testdb
#  username: skku
#  password: skku
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  generate-unique-name: false

spring.sql.init.mode: ALWAYS
spring.jpa:
  hibernate.ddl-auto: update
  defer-datasource-initialization: true
